#
# The 'XXX_DISABLE_' suffix is used twice in this file to disable two actions:
# 1) XXX_DISABLE_${CI_FILE_PUSH_IMAGE_TO_REPO} - disables pushing the rebuilt Docker image and
# 2) XXX_DISABLE_AUTO_DOC_UPDATE - disables making pull requests with the update of documentation.
# Those two actions are disabled, because they conflict with the same ones run on Travis.
# Only one CI (Travis or GitHub Actions) can run them at the time, so they can be enabled here,
# when we decide to switch from Travis to GitHub Actions. The 'XXX_DISABLE_' suffix should be removed then.
#

name: pmemkv
on: [push, pull_request]

env:
    REPO:           pmemkv
    GITHUB_REPO:    pmem/pmemkv
    DOCKERHUB_REPO: pmem/pmemkv

jobs:
  linux:
    name: pmemkv
    runs-on: ubuntu-latest
    env:
      HOST_WORKDIR:   /home/runner/work/pmemkv/pmemkv
      WORKDIR:        utils/docker
    strategy:
      matrix:
        CONFIG: ["TYPE=normal OS=fedora OS_VER=31",
                 "TYPE=normal OS=ubuntu OS_VER=19.10",
                 "TYPE=normal OS=ubuntu OS_VER=19.10 COVERAGE=1",
                 "TYPE=building OS=fedora OS_VER=31 COVERAGE=1 PUSH_IMAGE=1 XXX_DISABLE_AUTO_DOC_UPDATE=1",
                 "TYPE=building OS=ubuntu OS_VER=19.10 COVERAGE=1 PUSH_IMAGE=1",
                 "TYPE=bindings OS=ubuntu OS_VER=19.10_bindings PUSH_IMAGE=1",
                 "TYPE=compatibility OS=fedora OS_VER=31",
                 "TYPE=coverity OS=ubuntu OS_VER=19.10"]
    steps:
       - name: Clone the git repo
         uses: actions/checkout@v1

       - name: Pull or rebuild the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh

       - name: Run the build
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build.sh

       - name: Push the image
         run: cd $WORKDIR && source ./set-vars.sh && ${{ matrix.CONFIG }} /bin/bash -c "if [[ -f XXX_DISABLE_${CI_FILE_PUSH_IMAGE_TO_REPO} ]]; then images/push-image.sh $OS-$OS_VER; fi"
