
name: pmemkv-weekly
# It runs non-day-to-day checks; "unusual" jobs required to be checked only once in a while.

# instead of running it every week, it's now run only on-demand
on:
  workflow_dispatch:

env:
  REPO:           pmemkv
  GITHUB_REPO:    pmem/pmemkv
  CONTAINER_REG:  ghcr.io/pmem/pmemkv
  HOST_WORKDIR:   ${{ github.workspace }}
  WORKDIR:        utils/docker
  TEST_TIMEOUT:   900
  IMG_VER:        latest
  PUSH_IMAGE:     0

jobs:
  linux:
    name: Linux-weekly
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONFIG: ["TYPE=debug OS=ubuntu OS_VER=devel TESTS_ASAN=1 TESTS_PMREORDER=0",
                 "TYPE=debug OS=ubuntu OS_VER=devel TESTS_UBSAN=1 TESTS_PMREORDER=0",
                 "TYPE=debug OS=fedora OS_VER=34 TESTS_ASAN=1 TESTS_PMREORDER=0",
                 "TYPE=debug OS=fedora OS_VER=34 TESTS_UBSAN=1 TESTS_PMREORDER=0",
                 "TYPE=valgrind OS=fedora OS_VER=rawhide TESTS_PMREORDER=0",
                 "TYPE=memcheck_drd OS=fedora OS_VER=rawhide TESTS_PMREORDER=0",
                 "TYPE=building OS=fedora OS_VER=rawhide",
                 "TYPE=building OS=ubuntu OS_VER=devel"]
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v2

      # It rebuilds images every time (push is not neccessary; they are pushed in other workflows)
      - name: Rebuild the image
        run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh rebuild

      - name: Run the build
        run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build.sh
